### ISSUE TITLE
Looking for firmware for CTC with 1280

### ISSUE THREAD

**Issue by IckyBoBicky** [uoitalia/Sailfish-MightyBoardFirmware#4]
In the releases I can only see firmware for the CTC that is for the 2560 such as CTC_BizerMod-2560-Sailfish-v7.10.0-r1858.hex is there a 1280 release?

**Comment by SaschaKP** [comment]
Sorry for the late response, but I suppose I already answered on thingiverse, the firmware for 1280 is every name that doesn't have 2560 in it's name, plus, every HYPER marked firmware has the SAME functionality as the 2560 firmware that fits without any problem into the 1280 eeprom, you have to consider this:
2560 and 1280 have only a difference in the programmable memory, the volatile memory is of the same size.

Tell me if you want some other infos, in the meantime I'll close this issue, if in need or if you find any problem relative to this, I'll reopen it.

For CTC every replicator 1 firmware is good, it depends on your need, for autoleveling use replicator 1 with hyper.
