### ISSUE TITLE
Auto-level offsets for dual extruders

### ISSUE THREAD

**Issue by el0x00bre** [uoitalia/Sailfish-MightyBoardFirmware#6]
Not sure if I'm missing something but the auto-level XY offsets are only for one nozzle setups. As I have a dual extruder shall I just set it up with my most used nozzle?

**Comment by SaschaKP** [comment]
nope, you only need for the first nozzle (right one), as you have to issue all the commands for auto-leveling BEFORE nozzle selection (that would use first one as default), anyway, I suggest you to switch to a current and developed firmware, marlin, since I've done it too.

**Comment by el0x00bre** [comment]
Ofcourse, makes sense. Thanks! I’d like to upgrade but I’ve got an old Wanhao D4 on the ATMega 1260, thought this wasn’t supported by Marlin? Trying to avoid swapping out the board.

**Comment by SaschaKP** [comment]
ATMega 1280 has same specifics as ATMega 2560, it only changes the programmable memory size, so you have to remain under 128KBytes of progmem (minus an amount of bytes for the bootloader, that will remain the same), anyway, you'll need some know-how, if your printer currently works good, remain as you are. in both controller EEPROM size and SRAM are equal.

**Comment by SaschaKP** [comment]
as a reference:

Atmega1280:
low-power Microchip 8-bit AVR RISC-based microcontroller combines 128KB ISP flash memory, 8KB SRAM, 4KB EEPROM, 86 general purpose I/O lines, 32 general purpose working registers, real time counter, six flexible timer/counters with compare modes, PWM, 4 USARTs, byte oriented 2-wire serial interface, 16-channel 10-bit A/D converter, and a JTAG interface for on-chip debugging. The device achieves a throughput of 16 MIPS at 16 MHz and operates between 2.7-5.5 volts.

Atmega2560:
low-power Microchip 8-bit AVR RISC-based microcontroller combines 256KB ISP flash memory, 8KB SRAM, 4KB EEPROM, 86 general purpose I/O lines, 32 general purpose working registers, real time counter, six flexible timer/counters with compare modes, PWM, 4 USARTs, byte oriented 2-wire serial interface, 16-channel 10-bit A/D converter, and a JTAG interface for on-chip debugging. The device achieves a throughput of 16 MIPS at 16 MHz and operates between 4.5-5.5 volts.

**Comment by SaschaKP** [comment]
Anyway, I'll follow up this, I could compile a marlin version for the wanhao 4, after all it's almost same hardware, and I bet it can enter inside the progmem of the 1280, as my machine only differs for a few things, I only need a few specifications that you can grab from replicatorG, all the machine settings, (toolhead offset too for the second extruder, if you have more than one), and the plate size, I'll check if I can fit the firmware in that space.

Requirements:
- Toolhead offset for second extruder (usually something like -34.00 for wanhao with mk10)
- dimension of the buildplate
- if you're using the Z auto-leveling probe, I need to know it's position in space, comparing it's distance from the extruder to the right
- BAUD rate of the serial you're actually using.
- steps and anything you can see in replicatorG machine info/specs and in configuration info, anything, please.

**Comment by el0x00bre** [comment]
EDIT: Just wanted to say that you so much for offering but I managed to get it compiled myself. Currently have the same issue as you with the right Hotend not heating though...
